services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: lamoded
      MYSQL_ROOT_PASSWORD: lamoded
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - api-dockernet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v0
    volumes:
      - $HOME/nodeapp:/node-dir
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeapp-service
      SERVER_PORT: 3000
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: 'lamoded'
      DB_NAME: 'patientsdb'
      DB_CONNECTION_LIMIT: 20
    depends_on:
      - mysqldb
    networks:
      - api-dockernet

networks:
  api-dockernet:
    driver: bridge
