services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: lamoded
      MYSQL_ROOT_PASSWORD: lamoded
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - api-dockernet

networks:
  api-dockernet:
    driver: bridge
